repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.28.0
    hooks:
      - id: ruff
        args: ["--fix"]
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: ["--max-line-length=88"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        additional_dependencies: ["sqlmodel", "pydantic"]
