"""Revision ID: 7176100dd1ac
Revises:
Create Date: 2025-08-28 10:16:18.890363
"""  # noqa: D205, D400, D415

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "7176100dd1ac"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    """Upgrade the database schema.

    This migration changes the 'tags' column in the 'adapter' table from
    VARCHAR to JSONB for PostgreSQL, and JSON for other databases.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    dialect = op.get_bind().dialect.name
    if dialect == "postgresql":
        type_ = postgresql.JSONB(astext_type=sa.Text())
    else:
        type_ = sa.JSON()

    with op.batch_alter_table("adapter", schema=None) as batch_op:
        batch_op.alter_column(
            "tags", existing_type=sa.VARCHAR(), type_=type_, existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    """Downgrade the database schema.

    This migration reverts the 'tags' column in the 'adapter' table from
    JSON/JSONB back to VARCHAR.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    dialect = op.get_bind().dialect.name
    if dialect == "postgresql":
        existing_type = postgresql.JSONB(astext_type=sa.Text())
    else:
        existing_type = sa.JSON()

    with op.batch_alter_table("adapter", schema=None) as batch_op:
        batch_op.alter_column(
            "tags",
            existing_type=existing_type,
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
