"""Pydantic schemas for request/response models."""

from .adapters import (
    AdapterCreate,
    AdapterListResponse,
    AdapterRead,
    AdapterWrapper,
)
from .analytics import (
    ErrorAnalysisEntry,
    GenerationVolumePoint,
    PerformanceAnalyticsCharts,
    PerformanceAnalyticsSummary,
    PerformanceInsightEntry,
    PerformanceKpiSummary,
    PerformanceSeriesPoint,
    PerformanceTimeRange,
    ResourceUsagePoint,
)
from .common import (
    WebSocketMessage,
    WebSocketSubscription,
)
from .deliveries import (
    ComposeDelivery,
    ComposeDeliveryCLI,
    ComposeDeliveryHTTP,
    ComposeDeliveryInfo,
    ComposeRequest,
    ComposeResponse,
    DeliveryCreate,
    DeliveryCreateResponse,
    DeliveryRead,
    DeliveryWrapper,
)
from .generation import (
    ComposeDeliverySDNext,
    GenerationBulkDeleteRequest,
    GenerationCancelResponse,
    GenerationComplete,
    GenerationExportRequest,
    GenerationJobStatus,
    GenerationMode,
    GenerationResultFormat,
    GenerationResultSummary,
    GenerationStarted,
    ProgressUpdate,
    SDNextDeliveryParams,
    SDNextGenerationParams,
    SDNextGenerationResult,
)
from .import_export import (
    BackupCreateRequest,
    BackupHistoryItem,
    ExportConfig,
    ExportEstimate,
    ImportConfig,
)
from .recommendations import (
    BatchEmbeddingRequest,
    BatchEmbeddingResponse,
    EmbeddingStatus,
    IndexRebuildResponse,
    PromptRecommendationRequest,
    RecommendationFeedbackRead,
    RecommendationItem,
    RecommendationRequest,
    RecommendationResponse,
    RecommendationStats,
    SimilarityRequest,
    UserFeedbackRequest,
    UserPreferenceRead,
    UserPreferenceRequest,
)

__all__ = [
    # Adapters
    "AdapterCreate",
    "AdapterRead",
    "AdapterWrapper",
    "AdapterListResponse",
    # Analytics
    "PerformanceAnalyticsSummary",
    "PerformanceAnalyticsCharts",
    "PerformanceKpiSummary",
    "PerformanceInsightEntry",
    "ErrorAnalysisEntry",
    "PerformanceTimeRange",
    "GenerationVolumePoint",
    "PerformanceSeriesPoint",
    "ResourceUsagePoint",
    # Deliveries
    "ComposeDeliveryHTTP",
    "ComposeDeliveryCLI",
    "ComposeDelivery",
    "ComposeDeliveryInfo",
    "ComposeResponse",
    "ComposeRequest",
    "DeliveryCreate",
    "DeliveryRead",
    "DeliveryWrapper",
    "DeliveryCreateResponse",
    "ComposeDeliverySDNext",
    # Generation
    "GenerationMode",
    "GenerationResultFormat",
    "SDNextGenerationParams",
    "SDNextDeliveryParams",
    "SDNextGenerationResult",
    "ProgressUpdate",
    "GenerationStarted",
    "GenerationComplete",
    "GenerationJobStatus",
    "GenerationCancelResponse",
    "GenerationResultSummary",
    "GenerationBulkDeleteRequest",
    "GenerationExportRequest",
    # Import/export
    "ExportConfig",
    "ExportEstimate",
    "ImportConfig",
    "BackupHistoryItem",
    "BackupCreateRequest",
    # Recommendations
    "RecommendationRequest",
    "RecommendationResponse",
    "RecommendationItem",
    "PromptRecommendationRequest",
    "SimilarityRequest",
    "UserFeedbackRequest",
    "UserPreferenceRequest",
    "RecommendationFeedbackRead",
    "UserPreferenceRead",
    "RecommendationStats",
    "EmbeddingStatus",
    "BatchEmbeddingRequest",
    "BatchEmbeddingResponse",
    "IndexRebuildResponse",
    # Common
    "WebSocketMessage",
    "WebSocketSubscription",
]
