"""Add performance indexes.

Adds critical database indexes for frequently queried columns to improve performance:
- adapter.active: for filtering active/inactive adapters
- adapter.ordinal: for ordering active adapters in composition
- deliveryjob.status: for filtering jobs by status
- adapter.name: for name-based lookups and uniqueness checks
- adapter.created_at: for temporal queries and sorting

Revision ID: 952b85546fed
Revises: cbab2373ecb9
Create Date: 2025-08-29 09:00:12.906918
"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "952b85546fed"
down_revision = "cbab2373ecb9"
branch_labels = None
depends_on = None


def upgrade():
    """Apply performance index additions."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Add indexes for adapter table - critical for performance
    op.create_index("idx_adapter_active", "adapter", ["active"])
    op.create_index("idx_adapter_ordinal", "adapter", ["ordinal"])
    op.create_index("idx_adapter_name", "adapter", ["name"])
    op.create_index("idx_adapter_created_at", "adapter", ["created_at"])

    # Add composite index for active adapters ordered by ordinal
    # (most common query pattern)
    op.create_index("idx_adapter_active_ordinal", "adapter", ["active", "ordinal"])

    # Add indexes for deliveryjob table
    op.create_index("idx_deliveryjob_status", "deliveryjob", ["status"])
    op.create_index("idx_deliveryjob_created_at", "deliveryjob", ["created_at"])
    op.create_index("idx_deliveryjob_mode", "deliveryjob", ["mode"])

    # ### end Alembic commands ###


def downgrade():
    """Remove performance index additions."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop indexes in reverse order
    op.drop_index("idx_deliveryjob_mode", table_name="deliveryjob")
    op.drop_index("idx_deliveryjob_created_at", table_name="deliveryjob")
    op.drop_index("idx_deliveryjob_status", table_name="deliveryjob")
    op.drop_index("idx_adapter_active_ordinal", table_name="adapter")
    op.drop_index("idx_adapter_created_at", table_name="adapter")
    op.drop_index("idx_adapter_name", table_name="adapter")
    op.drop_index("idx_adapter_ordinal", table_name="adapter")
    op.drop_index("idx_adapter_active", table_name="adapter")

    # ### end Alembic commands ###
