"""Revision ID: cbab2373ecb9
Revises: d16f3e1df8bd
Create Date: 2025-08-28 21:03:36.796948.
"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "cbab2373ecb9"
down_revision = "d16f3e1df8bd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("adapter", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "json_file_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True
            )
        )
        batch_op.add_column(sa.Column("json_file_mtime", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("json_file_size", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("last_ingested_at", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("adapter", schema=None) as batch_op:
        batch_op.drop_column("last_ingested_at")
        batch_op.drop_column("json_file_size")
        batch_op.drop_column("json_file_mtime")
        batch_op.drop_column("json_file_path")

    # ### end Alembic commands ###
