name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  quality:
    name: Unified quality checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r dev-requirements.txt
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Install Node dependencies
        run: npm ci
      - name: Run unified quality workflow
        run: npm run ci:check

  node-modules-sanity:
    name: Ensure node_modules directory is absent
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Verify node_modules is not committed
        run: |
          if [ -d node_modules ]; then
            echo "node_modules/ should not be committed to the repository." >&2
            exit 1
          fi

  frontend-prod-build:
    name: Production build validation
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Build production bundle
        run: npm run prod:build
